// WHY: single source of truth for error codes — Constitution § 4.5 forbids inline strings.

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  AUTH_LOGIN_INVALID_CREDENTIALS: 'AUTH_LOGIN_INVALID_CREDENTIALS',
  AUTH_LOGIN_USER_INACTIVE: 'AUTH_LOGIN_USER_INACTIVE',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_NOT_FOUND: 'AUTH_REFRESH_TOKEN_NOT_FOUND',
  AUTH_REFRESH_TOKEN_REVOKED: 'AUTH_REFRESH_TOKEN_REVOKED',
  AUTH_REFRESH_TOKEN_EXPIRED: 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_REFRESH_TOKEN_REPLAY: 'AUTH_REFRESH_TOKEN_REPLAY',
  AUTH_FORBIDDEN_STORE: 'AUTH_FORBIDDEN_STORE',
  AUTH_FORBIDDEN_ROLE: 'AUTH_FORBIDDEN_ROLE',

  USER_CREATE_DUPLICATE_EMAIL: 'USER_CREATE_DUPLICATE_EMAIL',
  USER_DEACTIVATE_LAST_ADMIN: 'USER_DEACTIVATE_LAST_ADMIN',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_PASSWORD_TOO_SHORT: 'USER_PASSWORD_TOO_SHORT',
  USER_PASSWORD_RESET_BY_ADMIN: 'USER_PASSWORD_RESET_BY_ADMIN',

  ASSIGNMENT_DUPLICATE: 'ASSIGNMENT_DUPLICATE',
  ASSIGNMENT_NOT_FOUND: 'ASSIGNMENT_NOT_FOUND',
  ASSIGNMENT_LAST_REMOVAL_REQUIRES_CONFIRM: 'ASSIGNMENT_LAST_REMOVAL_REQUIRES_CONFIRM',
  ASSIGNMENT_STORE_NOT_FOUND: 'ASSIGNMENT_STORE_NOT_FOUND',
  ASSIGNMENT_INVALID_FOR_ADMIN: 'ASSIGNMENT_INVALID_FOR_ADMIN',

  STORE_NOT_FOUND: 'STORE_NOT_FOUND',
  STORE_DUPLICATE_CODE: 'STORE_DUPLICATE_CODE',
  STORE_HAS_ACTIVE_ASSIGNMENTS: 'STORE_HAS_ACTIVE_ASSIGNMENTS',
  STORE_WAREHOUSE_ALREADY_EXISTS: 'STORE_WAREHOUSE_ALREADY_EXISTS',
  STORE_KIND_INVALID: 'STORE_KIND_INVALID',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const AUDIT_CODES = {
  STORE_CREATED: 'STORE_CREATED',
  STORE_UPDATED: 'STORE_UPDATED',
  STORE_DEACTIVATED: 'STORE_DEACTIVATED',
  STORE_REACTIVATED: 'STORE_REACTIVATED',
} as const;

export type AuditCode = (typeof AUDIT_CODES)[keyof typeof AUDIT_CODES];
