// WHY: single source of truth for error codes — Constitution § 4.5 forbids inline strings.

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  AUTH_LOGIN_INVALID_CREDENTIALS: 'AUTH_LOGIN_INVALID_CREDENTIALS',
  AUTH_LOGIN_USER_INACTIVE: 'AUTH_LOGIN_USER_INACTIVE',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_NOT_FOUND: 'AUTH_REFRESH_TOKEN_NOT_FOUND',
  AUTH_REFRESH_TOKEN_REVOKED: 'AUTH_REFRESH_TOKEN_REVOKED',
  AUTH_REFRESH_TOKEN_EXPIRED: 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_REFRESH_TOKEN_REPLAY: 'AUTH_REFRESH_TOKEN_REPLAY',
  AUTH_FORBIDDEN_STORE: 'AUTH_FORBIDDEN_STORE',
  AUTH_FORBIDDEN_ROLE: 'AUTH_FORBIDDEN_ROLE',

  USER_CREATE_DUPLICATE_EMAIL: 'USER_CREATE_DUPLICATE_EMAIL',
  USER_DEACTIVATE_LAST_ADMIN: 'USER_DEACTIVATE_LAST_ADMIN',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_PASSWORD_TOO_SHORT: 'USER_PASSWORD_TOO_SHORT',
  USER_PASSWORD_RESET_BY_ADMIN: 'USER_PASSWORD_RESET_BY_ADMIN',

  ASSIGNMENT_DUPLICATE: 'ASSIGNMENT_DUPLICATE',
  ASSIGNMENT_NOT_FOUND: 'ASSIGNMENT_NOT_FOUND',
  ASSIGNMENT_LAST_REMOVAL_REQUIRES_CONFIRM: 'ASSIGNMENT_LAST_REMOVAL_REQUIRES_CONFIRM',
  ASSIGNMENT_STORE_NOT_FOUND: 'ASSIGNMENT_STORE_NOT_FOUND',
  ASSIGNMENT_INVALID_FOR_ADMIN: 'ASSIGNMENT_INVALID_FOR_ADMIN',

  STORE_NOT_FOUND: 'STORE_NOT_FOUND',
  STORE_DUPLICATE_CODE: 'STORE_DUPLICATE_CODE',
  STORE_HAS_ACTIVE_ASSIGNMENTS: 'STORE_HAS_ACTIVE_ASSIGNMENTS',
  STORE_WAREHOUSE_ALREADY_EXISTS: 'STORE_WAREHOUSE_ALREADY_EXISTS',
  STORE_KIND_INVALID: 'STORE_KIND_INVALID',

  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_DUPLICATE_CODE: 'PRODUCT_DUPLICATE_CODE',
  PRODUCT_HAS_ACTIVE_VARIANTS: 'PRODUCT_HAS_ACTIVE_VARIANTS',
  VARIANT_NOT_FOUND: 'VARIANT_NOT_FOUND',
  VARIANT_PRODUCT_NOT_FOUND: 'VARIANT_PRODUCT_NOT_FOUND',
  VARIANT_DUPLICATE_TUPLE: 'VARIANT_DUPLICATE_TUPLE',
  VARIANT_PRICE_REQUIRED: 'VARIANT_PRICE_REQUIRED',
  VARIANT_IMAGE_TOO_LARGE: 'VARIANT_IMAGE_TOO_LARGE',
  VARIANT_IMAGE_INVALID_TYPE: 'VARIANT_IMAGE_INVALID_TYPE',
  VARIANT_IMMUTABLE_FIELD: 'VARIANT_IMMUTABLE_FIELD',
  BARCODE_COLLISION: 'BARCODE_COLLISION',

  STOCK_NOT_FOUND: 'STOCK_NOT_FOUND',
  STOCK_BARCODE_NOT_FOUND: 'STOCK_BARCODE_NOT_FOUND',
  STOCK_VENDEDORA_EDIT_DISABLED: 'STOCK_VENDEDORA_EDIT_DISABLED',
  STOCK_NEGATIVE_NOT_ALLOWED: 'STOCK_NEGATIVE_NOT_ALLOWED',
  STORE_EDIT_PERMISSION_FORBIDDEN: 'STORE_EDIT_PERMISSION_FORBIDDEN',
  INVENTORY_PRODUCT_NOT_IN_STORE: 'INVENTORY_PRODUCT_NOT_IN_STORE',

  DELIVERY_NOT_FOUND: 'DELIVERY_NOT_FOUND',
  DELIVERY_NO_WAREHOUSE: 'DELIVERY_NO_WAREHOUSE',
  DELIVERY_INSUFFICIENT_STOCK: 'DELIVERY_INSUFFICIENT_STOCK',
  DELIVERY_EMPTY_ITEMS: 'DELIVERY_EMPTY_ITEMS',
  DELIVERY_VARIANT_NOT_FOUND: 'DELIVERY_VARIANT_NOT_FOUND',
  DELIVERY_FORBIDDEN: 'DELIVERY_FORBIDDEN',

  SALE_NOT_FOUND: 'SALE_NOT_FOUND',
  SALE_EMPTY_ITEMS: 'SALE_EMPTY_ITEMS',
  SALE_INSUFFICIENT_STOCK: 'SALE_INSUFFICIENT_STOCK',
  SALE_VARIANT_NOT_FOUND: 'SALE_VARIANT_NOT_FOUND',
  SALE_DASHBOARD_FORBIDDEN: 'SALE_DASHBOARD_FORBIDDEN',

  DAILY_REPORT_NOT_FOUND: 'DAILY_REPORT_NOT_FOUND',
  DAILY_REPORT_FORBIDDEN: 'DAILY_REPORT_FORBIDDEN',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const AUDIT_CODES = {
  STORE_CREATED: 'STORE_CREATED',
  STORE_UPDATED: 'STORE_UPDATED',
  STORE_DEACTIVATED: 'STORE_DEACTIVATED',
  STORE_REACTIVATED: 'STORE_REACTIVATED',

  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_DEACTIVATED: 'PRODUCT_DEACTIVATED',
  PRODUCT_REACTIVATED: 'PRODUCT_REACTIVATED',
  VARIANT_CREATED: 'VARIANT_CREATED',
  VARIANT_UPDATED: 'VARIANT_UPDATED',
  VARIANT_DEACTIVATED: 'VARIANT_DEACTIVATED',
  VARIANT_REACTIVATED: 'VARIANT_REACTIVATED',

  INVENTORY_QUANTITY_ADJUSTED: 'INVENTORY_QUANTITY_ADJUSTED',
  STORE_EDIT_PERMISSION_TOGGLED: 'STORE_EDIT_PERMISSION_TOGGLED',

  DELIVERY_CREATED: 'DELIVERY_CREATED',

  SALE_CREATED: 'SALE_CREATED',

  DAILY_REPORT_CLOSED: 'DAILY_REPORT_CLOSED',
} as const;

export type AuditCode = (typeof AUDIT_CODES)[keyof typeof AUDIT_CODES];
